import { useState } from 'react';
import type { EncryptionResult } from '../engine/types';
import { hex32 } from '../engine/uint';
import type { Mode } from './Workspace';
export function DiagnosticPanel({ result, mode, errorDetail }: { result?: EncryptionResult; mode: Mode; errorDetail: string }) {
  const [showWiring, setShowWiring] = useState(false);
  const values = result ? [
    ['Signature A', '0x' + hex32(result.signatureA)], ['Signature B', '0x' + hex32(result.signatureB)], ['Checksum', '0x' + hex32(result.checksum)], ['Plaintext byte length', result.plaintextBytes], ['Noise count', result.noiseBytes], ['Body length', result.bodyBytes], ['Total rotor mutations', result.totalMutations], ['Final rotor positions', result.rotorStates.map(rotor => String(rotor.position).padStart(3, '0')).join(' ')], ['Final rotor directions', result.rotorStates.map(rotor => rotor.direction === 1 ? '→' : '←').join(' ')],
  ] : [];
  return <details className="diagnostics"><summary><span><span className="section-number">04</span> DIAGNOSTIC MODE</span><span className="diagnostic-hint">INTERNAL MACHINE STATE <span className="details-chevron">+</span></span></summary><div className="diagnostic-content">{errorDetail && <p className="diagnostic-error">Validation detail: {errorDetail}</p>}{!result ? <p className="empty-diagnostic">Brak zweryfikowanego wyniku. Zainicjalizuj maszynę, aby zobaczyć jej stan.</p> : <><dl className="diagnostic-values">{values.map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="byte-diagnostic"><h3>LAST PROCESSED BYTE</h3>{result.diagnostic ? <div className="byte-values">{result.diagnostic.chain.map((value, i) => <span key={i}>r{i}<b>R{String(value).padStart(2, '0')}</b></span>)}{(['t0', 't1', 't2'] as const).map(label => <span key={label}>{label}<b>{result.diagnostic![label]}</b></span>)}<span>{mode === 'encrypt' ? 'input byte' : 'core input byte'}<b>{mode === 'encrypt' ? result.diagnostic.inputByte : result.diagnostic.coreOutputByte}</b></span><span>{mode === 'encrypt' ? 'core output byte' : 'recovered plaintext byte'}<b>{mode === 'encrypt' ? result.diagnostic.coreOutputByte : result.diagnostic.inputByte}</b></span></div> : <p className="empty-diagnostic">Pusta wiadomość — brak przetworzonych bajtów core.</p>}</div><button type="button" className="wiring-button" aria-expanded={showWiring} onClick={() => setShowWiring(!showWiring)}>{showWiring ? 'HIDE ROTOR WIRING' : 'SHOW ROTOR WIRING'}</button>{showWiring && <div className="wiring-list">{result.rotorStates.map(rotor => <details key={rotor.index}><summary>R{String(rotor.index).padStart(2, '0')} / {rotor.role} / 256 CONTACTS</summary><pre>{Array.from(rotor.wiring).map(value => String(value).padStart(3, '0')).join(' ')}</pre></details>)}</div>}</>}</div></details>;
}
