import React from 'react';
import './BuildVersion.css';

// Generated by `scripts/gen-build-info.cjs` during `prestart`/`prebuild`.
import { BUILD_INFO } from './buildInfo.generated';

export default function BuildVersion() {
  const version = BUILD_INFO?.version || 'v0.000';
  const sha = BUILD_INFO?.sha ? ` (${String(BUILD_INFO.sha)})` : '';
  return (
    <div className="build-version" aria-label="Site version">
      {version}{sha}
    </div>
  );
}
