
const mockFightData = [
  {
    category: "Walka Wieczoru",
    fights: [
      {
        id: 1,
        user1: "Użytkownik A",
        user2: "Użytkownik B",
        fighter1: "Superman",
        fighter2: "Goku",
        user1Record: "5-0",
        user2Record: "4-1",
        overallRecord1: "12-2",
        overallRecord2: "10-3",
      },
    ],
  },
  {
    category: "Co-Main Event",
    fights: [
      {
        id: 2,
        user1: "Użytkownik C",
        user2: "Użytkownik D",
        fighter1: "Batman",
        fighter2: "Joker",
        user1Record: "3-1",
        user2Record: "2-2",
        overallRecord1: "8-4",
        overallRecord2: "7-5",
      },
    ],
  },
  {
    category: "Main Card",
    fights: [
      {
        id: 3,
        user1: "Użytkownik E",
        user2: "Użytkownik F",
        fighter1: "Thor",
        fighter2: "Vegeta",
        user1Record: "4-0",
        user2Record: "3-1",
        overallRecord1: "9-1",
        overallRecord2: "6-2",
      },
      {
        id: 4,
        user1: "Użytkownik G",
        user2: "Użytkownik H",
        fighter1: "Wonder Woman",
        fighter2: "Sailor Moon",
        user1Record: "2-2",
        user2Record: "1-3",
        overallRecord1: "5-5",
        overallRecord2: "4-6",
      },
      {
        id: 5,
        user1: "Użytkownik I",
        user2: "Użytkownik J",
        fighter1: "Iron Man",
        fighter2: "Optimus Prime",
        user1Record: "1-0",
        user2Record: "0-1",
        overallRecord1: "3-0",
        overallRecord2: "2-1",
      },
    ],
  },
  {
    category: "Under Card",
    fights: [
      {
        id: 6,
        user1: "Użytkownik K",
        user2: "Użytkownik L",
        fighter1: "Spider-Man",
        fighter2: "Deadpool",
        user1Record: "0-0",
        user2Record: "0-0",
        overallRecord1: "1-1",
        overallRecord2: "0-2",
      },
      {
        id: 7,
        user1: "Użytkownik M",
        user2: "Użytkownik N",
        fighter1: "Hulk",
        fighter2: "Doomsday",
        user1Record: "0-0",
        user2Record: "0-0",
        overallRecord1: "2-0",
        overallRecord2: "1-1",
      },
      {
        id: 8,
        user1: "Użytkownik O",
        user2: "Użytkownik P",
        fighter1: "Captain America",
        fighter2: "Bane",
        user1Record: "0-0",
        user2Record: "0-0",
        overallRecord1: "0-0",
        overallRecord2: "0-0",
      },
      {
        id: 9,
        user1: "Użytkownik Q",
        user2: "Użytkownik R",
        fighter1: "Black Widow",
        fighter2: "Harley Quinn",
        user1Record: "0-0",
        user2Record: "0-0",
        overallRecord1: "0-0",
        overallRecord2: "0-0",
      },
      {
        id: 10,
        user1: "Użytkownik S",
        user2: "Użytkownik T",
        fighter1: "Flash",
        fighter2: "Quicksilver",
        user1Record: "0-0",
        user2Record: "0-0",
        overallRecord1: "0-0",
        overallRecord2: "0-0",
      },
    ],
  },
];

export default mockFightData;
